vim.cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'folke/tokyonight.nvim'
  use 'easymotion/vim-easymotion'
  use 'belltoy/vim-protobuf'
  use 'tpope/vim-fugitive'
  use 'godlygeek/csapprox'
  use 'scrooloose/nerdtree'
  use 'flazz/vim-colorschemes'
  use 'mattn/emmet-vim'
  use 'elzr/vim-json'
  use 'kien/ctrlp.vim'
  use 'ConradIrwin/vim-bracketed-paste'
  use 'udalov/kotlin-vim'
  use 'hashivim/vim-terraform'
  use 'neovim/nvim-lspconfig'
  use 'williamboman/mason.nvim'
  use 'williamboman/mason-lspconfig.nvim'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/nvim-cmp'
  use 'L3MON4D3/LuaSnip'
end)
